version: "3.7"

volumes:
  dbdata:

services:
  crawler:
    container_name: wikihotel-crawler
    image: nginx:stable-alpine
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - "./config/nginx:/etc/nginx/conf.d"
      - "./log/nginx:/var/log/nginx"
    depends_on:
      - backend
    links:
      - backend
    restart: always

  database:
    container_name: oee-nabati-database
    image: mariadb:latest
    volumes:
      - "./config/mysql:/etc/mysql/conf.d"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    restart: always

  adminer:
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

  api:
    build:
      context: ./apiserver
      dockerfile: dev.dockerfile
    working_dir: /var/www
    volumes:
      - ./apiserver:/var/www
    restart: always

  web:
    build:
      context: ./
      dockerfile: nginx-server.dockerfile
    working_dir: /var/www
    # volumes_from:
    #   - api
    ports:
      - 8080:80
